### ISSUE TITLE
Logistic_Mandelbrot.py Crashes Due to Vispy

### ISSUE THREAD

**Issue by redbear44** [jonnyhyman/Chaos#12]
Whenever I try and run logistic_mandelbrot.py I get an error saying "KeyError: 'colormap name nipy_spectral_r not found'" and is occurring in the colormap.py file within Vispy. I initially tried with python 3.8 but then tried 3.7 as well with no luck.

The whole error...

"Traceback (most recent call last):
  File "logistic_mandelbrot.py", line 452, in <module>
    volume1 = scene.visuals.Volume(vol, parent = view.scene,
  File "C:\Users\pjchu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\vispy\scene\visuals.py", line 127, in __init__
    subclass.__init__(self, *args, **kwargs)
  File "C:\Users\pjchu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\vispy\visuals\volume.py", line 411, in __init__
    self._cmap = get_colormap(cmap)
  File "C:\Users\pjchu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\vispy\color\colormap.py", line 1120, in get_colormap
    raise KeyError('colormap name %s not found' % name)
KeyError: 'colormap name nipy_spectral_r not found'"

**Comment by jonnyhyman** [comment]
I think you forgot to install matplotlib! Try `pip3 install matplotlib`! 

`nipy_spectral_r` is a [colormap from matplotlib](https://matplotlib.org/3.1.0/tutorials/colors/c…)

**Comment by redbear44** [comment]
Well, now I just feel dumb haha. Must have forgotten to redownload it after reinstalling anaconda.

Thanks and amazing application!
