### ISSUE TITLE
Logistic Mandelbrot module throwing file not found errors

### ISSUE THREAD

**Issue by mandelbrotsf** [jonnyhyman/Chaos#38]
Pasting trimmed error output below:
Traceback (most recent call last):
  File "/Users/[XXXX]/Chaos/logistic_mandelbrot.py", line 349, in <module>
    vol = np.load(datafile)['data']
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
**FileNotFoundError: [Errno 2] No such file or directory: './data/fractal_mandelbrot_data100_iter1500_ovs1.npz'**

**Comment by AnonRZZGH** [comment]
check this #5

**Comment by jonnyhyman** [comment]
Solved by #5
