### ISSUE TITLE
Error in setValues     self.rate.setValue( linear_interp(self.rateval,

### ISSUE THREAD

**Issue by Shivam-bot-glitch** [jonnyhyman/Chaos#44]
Traceback (most recent call last):
  File "D:\Atom\Chaos-master\logistic_interactive.py", line 480, in <lambda>
    self.rate_box.valueChanged.connect(lambda: self.setValues('rate_box'))
  File "D:\Atom\Chaos-master\logistic_interactive.py", line 533, in setValues
    self.rate.setValue( linear_interp(self.rateval,
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "D:\Atom\Chaos-master\logistic_interactive.py", line 746, in <module>
    w = Widget(app)
  File "D:\Atom\Chaos-master\logistic_interactive.py", line 575, in __init__
    self.controls.setValues()
  File "D:\Atom\Chaos-master\logistic_interactive.py", line 560, in setValues
    self.setValues('rate_box')
  File "D:\Atom\Chaos-master\logistic_interactive.py", line 533, in setValues
    self.rate.setValue( linear_interp(self.rateval,
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

C:\WINDOWS\system32>D:\Atom\Chaos-master\logistic_setValues.py
'D:\Atom\Chaos-master\logistic_setValues.py' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>    self.rate.setValue( linear_interp(self.rateval,
'self.rate.setValue' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jonnyhyman** [comment]
You're running the file incorrectly, instead of just running `D:\Atom\Chaos-master\logistic_setValues.py` try running `python D:\Atom\Chaos-master\logistic_setValues.py`
