### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by davecotter** [jonnyhyman/Chaos#52]
```
pandora:Chaos davec$ python3 logistic_interactive.py
Traceback (most recent call last):
  File "/Volumes/Developer/depot/Chaos/logistic_interactive.py", line 13, in <module>
    from PyQt5.QtCore import Qt
ModuleNotFoundError: No module named 'PyQt5'
pandora:Chaos davec$ 

```

**Comment by davecotter** [comment]
```
pandora:Chaos davec$ pip install -U PySide
Collecting PySide
  Downloading PySide-1.2.4.tar.gz (9.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 10.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
pandora:Chaos davec$ 

```

**Comment by davecotter** [comment]
please i am having DREAMS about this bifurcation plot, i really NEED to see this for myself! pretty please! for SCIENCE!!!

**Comment by jonnyhyman** [comment]
run `pip install PyQt5` not PySide

**Comment by davecotter** [comment]
```
pandora:Chaos davec$ pip install PyQt5
Collecting PyQt5
  Downloading PyQt5-5.15.9.tar.gz (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 10.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/wj/h6k40dgn4sq6l98trqd3qlyh0000gn/T/pip-build-env-os5ewdgj/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/wj/h6k40dgn4sq6l98trqd3qlyh0000gn/T/pip-build-env-os5ewdgj/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/wj/h6k40dgn4sq6l98trqd3qlyh0000gn/T/pip-build-env-os5ewdgj/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/wj/h6k40dgn4sq6l98trqd3qlyh0000gn/T/pip-install-go_sb_2f/pyqt5_01dd83ba6ed94083ae3b55388d80247d/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/wj/h6k40dgn4sq6l98trqd3qlyh0000gn/T/pip-build-env-os5ewdgj/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/wj/h6k40dgn4sq6l98trqd3qlyh0000gn/T/pip-build-env-os5ewdgj/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/wj/h6k40dgn4sq6l98trqd3qlyh0000gn/T/pip-build-env-os5ewdgj/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
pandora:Chaos davec$ 

```

**Comment by jonnyhyman** [comment]
as this is a pyqt5 install issue, I would suggest posting your issue on their forums instead of here!
