### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by tntmaster1983** [jonnyhyman/Chaos#6]
I get this error when I boot the logistic_interactive.py file
Traceback (most recent call last):
  File "logistic_interactive.py", line 19, in <module>
    import pyqtgraph as pg
  File "C:\Python38\lib\site-packages\pyqtgraph\__init__.py", line 204, in <module>
    from .graphicsItems.VTickGroup import *
  File "C:\Python38\lib\site-packages\pyqtgraph\graphicsItems\VTickGroup.py", line 7, in <module>
    from .. import functions as fn
  File "C:\Python38\lib\site-packages\pyqtgraph\functions.py", line 17, in <module>
    from . import debug
  File "C:\Python38\lib\site-packages\pyqtgraph\debug.py", line 11, in <module>
    from . import ptime
  File "C:\Python38\lib\site-packages\pyqtgraph\ptime.py", line 24, in <module>
    cstart = systime.clock()  ### Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'

**Comment by Jeyekomon** [comment]
@tntmaster1983 
The `pyqtgraph` package had some issues with `Python 3.8`:
https://github.com/pyqtgraph/pyqtgraph/pull/980

**Comment by jonnyhyman** [comment]
Thanks @Jeyekomon, @tntmaster1983 reccomend downgrading to 3.6 or 3.7 (where the codes have been tested)

**Comment by tntmaster1983** [comment]
Thanks that fixed the problem.
